US_GAPP_TAGS_LIST = ['EarningsPerShareDiluted',
                     'EarningsPerShareBasic',
                     'GrossProfit',
                     'NetIncomeLoss',
                     'IncomeTaxExpenseBenefit',
                     'StockholdersEquity',
                     'CapitalExpenditure',
                     'CashFlowFromOperations',
                     'Revenues',
                     'CostOfGoodsAndServicesSold',
                     'SellingGeneralAndAdministrativeExpense',
                     'ResearchAndDevelopmentExpense',
                     'DepreciationAndAmortization',
                     'IncreaseDecreaseInAccountsPayable',
                     'IncreaseDecreaseInAccountsReceivable',
                     'OperatingIncomeLoss',
                     'LongTermDebtNoncurrent',
                     'NumberOfDilutedShares',
                     'NumberOfShares']

ALTERNATIVE_TAG_NAMES = {'Revenues': ['SalesRevenueNet', 'RevenueFromContractWithCustomerExcludingAssessedTax', 'SalesRevenueGoodsNet'],
                         'CashFlowFromOperations': 'NetCashProvidedByUsedInOperatingActivities',
                         'NetIncomeLoss': 'NetIncomeLossAvailableToCommonStockholdersBasic',
                         'CapitalExpenditure': ['PaymentsToAcquirePropertyPlantAndEquipment', 'PaymentsToAcquireProductiveAssets'],
                         'CostOfGoodsAndServicesSold': 'CostOfRevenue',
                         'DepreciationAndAmortization': 'DepreciationDepletionAndAmortization',
                         'NumberOfDilutedShares': 'WeightedAverageNumberOfDilutedSharesOutstanding',
                         'NumberOfShares': 'WeightedAverageNumberOfSharesOutstandingBasic'}
