US_GAPP_TAGS_LIST = ['EarningsPerShareDiluted',
                     'EarningsPerShareBasic',
                     'GrossProfit',
                     'NetIncomeLoss',
                     'IncomeTaxExpenseBenefit',
                     'StockholdersEquity',
                     'CapitalExpenditure',
                     'CashFlowFromOperations',
                     'Revenues',
                     'CostOfGoodsAndServicesSold',
                     'SellingGeneralAndAdministrativeExpense',
                     'ResearchAndDevelopmentExpense',
                     'DepreciationAndAmortization',
                     'IncreaseDecreaseInAccountsPayable',
                     'IncreaseDecreaseInAccountsReceivable',
                     'OperatingIncomeLoss',
                     'LongTermDebt',
                     'CurrentDebt',
                     'Cash',
                     'TaxRate',
                     'NumberOfDilutedShares',
                     'NumberOfShares']

ALTERNATIVE_TAG_NAMES = {'Revenues': ['SalesRevenueNet', 'SalesRevenueGoodsNet', 'RevenueFromContractWithCustomerIncludingAssessedTax', 'RevenueFromContractWithCustomerExcludingAssessedTax'],
                         'CashFlowFromOperations': ['NetCashProvidedByUsedInOperatingActivities', 'NetCashProvidedByUsedInOperatingActivitiesContinuingOperations'],
                         'NetIncomeLoss': ['NetIncomeLossAvailableToCommonStockholdersBasic', 'ProfitLoss'],
                         'CapitalExpenditure': ['PaymentsToAcquirePropertyPlantAndEquipment', 'PaymentsToAcquireProductiveAssets'],
                         'CostOfGoodsAndServicesSold': 'CostOfRevenue',
                         'StockholdersEquity': 'StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest',
                         'DepreciationAndAmortization': 'DepreciationDepletionAndAmortization',
                         'EarningsPerShareDiluted': 'EarningsPerShareBasicAndDiluted',
                         'EarningsPerShareBasic': 'EarningsPerShareBasicAndDiluted',
                         'CurrentDebt': 'LongTermDebtAndCapitalLeaseObligationsCurrent',
                         'LongTermDebt': ['LongTermDebtNoncurrent', 'LongTermDebtAndCapitalLeaseObligations'],
                         'TaxRate': 'EffectiveIncomeTaxRateContinuingOperations',
                         'Cash': 'CashAndCashEquivalentsAtCarryingValue',
                         'NumberOfDilutedShares': ['WeightedAverageNumberOfDilutedSharesOutstanding', 'WeightedAverageNumberOfShareOutstandingBasicAndDiluted'],
                         'NumberOfShares': ['WeightedAverageNumberOfSharesOutstandingBasic', 'WeightedAverageNumberOfShareOutstandingBasicAndDiluted', 'CommonStocksIncludingAdditionalPaidInCapital']}
